Repository TDRMinecraft/TDRStudios-Lobby-5, pull requests merged in 2021-03, with the labels that each got.

#31 Update WorkOn_Navigator to avoid more conflicts
  .gitignore
  src/main/java/LobbyMaintenanceCommand.png
  src/main/java/LobbyPlugin.png
  src/main/java/Package lobbyplugin.png
  src/main/java/Package lobbyplugin2.png
  src/main/java/de/tdrstudios/lobbyplugin/Chat.java
  src/main/java/de/tdrstudios/lobbyplugin/LobbyPlugin.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/CommandMethods.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/LobbyMaintenanceCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/MyCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/SpawnCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/SpawnSetter.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/VersionCheckCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/enums/FormatType.java
  src/main/java/de/tdrstudios/lobbyplugin/enums/SenderType.java
  src/main/java/de/tdrstudios/lobbyplugin/events/GeneralEvents.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/CompassNavigator.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/MappedType.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/FormatMessage.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/Message.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/MessageManager.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/OnlySenderMessage.java
  src/main/java/de/tdrstudios/lobbyplugin/tabcomplete/TabComplete.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/SoundUtils.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/config/ConfigUtils.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/inventory/InventoryContent.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/inventory/InventoryUtils.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/inventory/navigator/NavigatorUtils.java
  src/main/java/test.png
  src/main/java/test/testmaster/devtools/MyPlayer.java
  src/main/java/test/testmaster/devtools/test.java
  src/main/resources/plugin.yml
  target/classes/debug/debug_output.tdrstudios
  target/classes/permissions.md
  target/classes/plugin.yml
Labels: Recode, enhancement

#46 Add DebugConsole.java
  src/main/java/de/tdrstudios/additional/BetaError.java
  src/main/java/de/tdrstudios/additional/debug/DebugConsole.java
  src/main/java/de/tdrstudios/lobbyplugin/LobbyPlugin.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/CompassNavigator.java
Labels: enhancement

#27 Feature/fix for #26
  src/main/java/de/tdrstudios/lobbyplugin/enums/FormatType.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/FormatMessage.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/Message.java
  src/main/java/de/tdrstudios/lobbyplugin/msgs/MessageManager.java
Labels: enhancement, processing

#48 Add better Debug Tools - Point.java
  src/main/java/de/tdrstudios/additional/debug/Point.java
  src/main/java/de/tdrstudios/additional/debug/PointTrace.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/VersionCheckCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/CompassNavigator.java
  src/main/java/test/testmaster/devtools/Main.java
  target/classes/plugin.yml
Labels: enhancement, refresh merge

#50 First update of WorkOn_Navigator3
  .gitignore
  src/main/java/de/tdrstudios/additional/debug/Point.java
  src/main/java/de/tdrstudios/lobbyplugin/Chat.java
  src/main/java/de/tdrstudios/lobbyplugin/LobbyPlugin.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/GamemodeCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/SpawnCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/SpawnSetter.java
  src/main/java/de/tdrstudios/lobbyplugin/events/GeneralEvents.java
  src/main/java/de/tdrstudios/lobbyplugin/events/HideStickCooldownOperation.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/CompassNavigator.java
  src/main/java/de/tdrstudios/lobbyplugin/inventory/SettingsInventory.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/config/ConfigUtils.java
  src/main/resources/plugin.yml
  target/classes/plugin.yml
Labels: CleanUp#1, Recode, bug, high priority, refresh merge

#54 Refresh bommels
  DevTools/DevTools_1.2.jar
  src/main/java/de/tdrstudios/lobbyplugin/LobbyPlugin.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/CommandMethods.java
  src/main/java/de/tdrstudios/lobbyplugin/commands/GamemodeCommand.java
  src/main/java/de/tdrstudios/lobbyplugin/events/GeneralEvents.java
  src/main/java/de/tdrstudios/lobbyplugin/tabcomplete/TabComplete.java
  src/main/java/de/tdrstudios/lobbyplugin/utils/KickUtils.java
  src/main/java/test/testmaster/TestCommand.java
  src/main/resources/plugin.yml
  target/classes/plugin.yml
Labels: refresh merge
